create database CineAPI

use CineAPI

CREATE TABLE USER_GENEROS
(
USERGEN_ID INT IDENTITY(1,1) PRIMARY KEY,
USREGEN_DESCRIP VARCHAR(100) not null
)

CREATE TABLE USUARIOS
(
USER_GUID VARCHAR(250) PRIMARY KEY,
USER_NOMBRE VARCHAR(40) not null,
USER_APELLIDO VARCHAR(40) not null,
USER_CORREO VARCHAR(50) UNIQUE,
USER_FECNAC DATETIME,
USER_TELEFONO VARCHAR(15),
USER_GENERO INT not null,
USER_RECALERT BIT not null
FOREIGN KEY (USER_GENERO) REFERENCES USER_GENEROS(USERGEN_ID)
)

CREATE TABLE GENEROS
(
GENERO_ID INT IDENTITY(1,1) PRIMARY KEY,
GENERO_DESCRIP VARCHAR(100) not null
)

CREATE TABLE PELICULAS
(
PELI_GUID VARCHAR(250) PRIMARY KEY,
PELI_TITULO VARCHAR(50) not null,
PELI_DESCRIP TEXT not null,
PELI_POSTER VARCHAR(250),
PELI_GENEROID INT not null,
FOREIGN KEY (PELI_GENEROID) REFERENCES GENEROS(GENERO_ID)
)

CREATE TABLE SALAS
(
SALA_ID INT IDENTITY(1,1) PRIMARY KEY,
SALA_NOMBRE VARCHAR(50) not null,
SALA_CAPACIDAD INT
)

CREATE TABLE ASIENTOS
(
ASIENTO_GUID VARCHAR(250) PRIMARY KEY,
ASIENTO_SALAID INT not null,
ASIENTO_FILA INT not null,
ASIENTO_NRO INT not null
FOREIGN KEY (ASIENTO_SALAID) REFERENCES SALAS(SALA_ID)
)

CREATE TABLE FUNCIONES
(
FUNCION_GUID VARCHAR(250) PRIMARY KEY,
FUNCION_PELIGUID VARCHAR(250) not null,
FUNCION_SALAID INT not null,
FUNCION_FECHA DATETIME not null,
FUNCION_HORA TIME not null,
FUNCION_DURACION TIME not null
FOREIGN KEY (FUNCION_PELIGUID) REFERENCES PELICULAS(PELI_GUID),
FOREIGN KEY (FUNCION_SALAID) REFERENCES SALAS(SALA_ID)
)

CREATE TABLE RESERVAS
(
RESER_GUID VARCHAR(250) PRIMARY KEY,
RESER_USRCORREO VARCHAR(50) not null,
RESER_FUNCIONGUID VARCHAR(250) not null,
RESER_FECHA DATETIME not null
FOREIGN KEY (RESER_USRCORREO) REFERENCES USUARIOS(USER_CORREO),
FOREIGN KEY (RESER_FUNCIONGUID) REFERENCES FUNCIONES(FUNCION_GUID)
)

CREATE TABLE ASIENTOS_RESERVADOS
(
ARESER_GUID VARCHAR(250) PRIMARY KEY,
ARESER_FUNCIONGUID VARCHAR(250) not null,
ARESER_RESERGUID VARCHAR(250) not null,
ARESER_ASIENTOGUID VARCHAR(250) not null,
FOREIGN KEY (ARESER_FUNCIONGUID) REFERENCES FUNCIONES(FUNCION_GUID),
FOREIGN KEY (ARESER_RESERGUID) REFERENCES RESERVAS(RESER_GUID),
FOREIGN KEY (ARESER_ASIENTOGUID) REFERENCES ASIENTOS(ASIENTO_GUID)
)

CREATE TABLE ROLES
(
ROL_ID INT IDENTITY(1,1) PRIMARY KEY,
ROL_NOMBRE VARCHAR(50) NOT NULL
)

CREATE TABLE ROLES_USUARIOS (
ROLUSER_ID INT IDENTITY(1,1) PRIMARY KEY,
ROLUSER_CORREO VARCHAR(50) NOT NULL,
ROLUSER_ROLID INT NOT NULL,
FOREIGN KEY (ROLUSER_CORREO) REFERENCES USUARIOS(USER_CORREO),
FOREIGN KEY (ROLUSER_ROLID) REFERENCES ROLES(ROL_ID),
);

CREATE TABLE CREDENCIALES
(
CREDEN_ID int IDENTITY(1,1) primary key,
CREDEN_CORREO VARCHAR(50) NOT NULL,
CREDEN_PASSWORD VARCHAR(200) NOT NULl,
FOREIGN KEY (CREDEN_CORREO) REFERENCES USUARIOS(USER_CORREO)
)




insert into USER_GENEROS(USREGEN_DESCRIP)
values ('Masculino'),('Femenino'),('Otro'),('Prefiero no especificarlo')

INSERT INTO GENEROS(GENERO_DESCRIP)
VALUES 
    ('Acción'),
    ('Aventura'),
    ('Comedia'),
    ('Drama'),
    ('Terror'),
    ('Ciencia Ficción'),
    ('Fantasía'),
    ('Romance'),
    ('Documental'),
    ('Animación');

insert into SALAS(SALA_NOMBRE,SALA_CAPACIDAD)
values('Sala 1',15)

insert into SALAS(SALA_NOMBRE,SALA_CAPACIDAD)
values('Sala 2',10)

insert into SALAS(SALA_NOMBRE,SALA_CAPACIDAD)
values('Sala 3',30)

insert into ASIENTOS(ASIENTO_GUID, ASIENTO_SALAID, ASIENTO_FILA, ASIENTO_NRO)
values(NEWID(),3,3,1),
(NEWID(),3,3,2),
(NEWID(),3,3,3),
(NEWID(),3,3,4),
(NEWID(),3,3,5),
(NEWID(),3,3,6),
(NEWID(),3,3,7),
(NEWID(),3,3,8),
(NEWID(),3,3,9),
(NEWID(),3,3,10)

INSERT INTO ROLES(ROL_NOMBRE)
VALUES('ADMIN')


select * from USUARIOS

select * from ROLES_USUARIOS

select * from CREDENCIALES

select * from FUNCIONES

insert into PELICULAS(PELI_GUID,PELI_TITULO,PELI_DESCRIP, PELI_POSTER, PELI_GENEROID)
VALUES('109e299c-f652-4393-bfcf-eb4811f432cf','Avenger:doomsday','Catorce meses después de los eventos de Thunderbolts* (2025), los Vengadores, los wakandianos, los Cuatro Fantásticos, los Nuevos Vengadores y los X-Men originales se unen para enfrentarse al Doctor Muerte','https://localhost:7151/posterPeliculas/668d04d5-b1f5-4c2c-83f6-2cd9cdf19815.PNG',1)




